# Generated by Django 4.0.4 on 2022-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@navertg.dkw', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
