# Generated by Django 4.0.4 on 2022-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@naegae.com', max_length=128, verbose_name='사용자이메일'),
        ),
    ]
